server {
    listen 80;
    index index.php index.html;

    # Point ke Laravel public folder
    root /var/www/public;

    # Log files
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    location / {
        # Cuba cari file, kalau tak jumpa hantar ke index.php (Laravel router)
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # Hantar PHP request ke container app (port 9000)
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Block akses ke hidden files (.env, .git etc)
    location ~ /\.(?!well-known).* {
        deny all;
    }
}